### ISSUE TITLE
Can I use this repo to detect m3u8 link from a URL.

### ISSUE THREAD

**Issue by zydjohnHotmail** [hmlendea/stream-to-m3u#29]
Hello:
I can use Chrome extension: m3u8 Sniffer to detect a M3U8 link when I launch web browser to visit a URL.
For example, this URL:
https://www.radiosvoboda.org/a/video-odesa-viyna-liudy/31766801.html
With m3u8 Sniffer, I can see the M3U8 link is:
https://rferl-vh.akamaihd.net/i/Pangeavideo/2022/03/8/84/8496aef7-5bc1-41a6-8609-fd20dcd3a75e,_240p,,_480p,_720p,.mp4.csmil/master.m3u8
Let me know if I can use the repo to do the same thing.
Thanks,

**Comment by hmlendea** [comment]
Hello.

Yes, this tool is supposed to do the same but only works with the services mentioned in the readme, and anything else is hit or miss.

Though, note that I haven't really been working on this tool for the past two years, so I don't know how well it would work today.
